### ISSUE TITLE
Execução dentro do Docker

### ISSUE THREAD

**Issue by lucasa** [EsauM10/fogbed#1]
Olá!
Seria possível executar essa versão do fogbed dentro do docker?
Como posso fazer?

Obrigado!

**Comment by EsauM10** [comment]
Acredito que sim.

Embora nunca tenha tentado, bastaria instalar o Containernet e o fogbed através de um Dockerfile.

Devido a problemas de limitação de recursos com nested containers conforme: https://github.com/containernet/containernet,
eu recomendo fortemente a instalação em uma máquina virtual para ter acesso a todas as features disponíveis no fogbed.
