### ISSUE TITLE
Erro ao Executar em VM Xubuntu 22.10

### ISSUE THREAD

**Issue by lucasa** [EsauM10/fogbed#2]
Olá Devs!
Estou tentando rodar o Fogbed em uma VM Xubuntu 22.10 mas um erro relacionado a cgroups está ocorrendo. O que posso fazer?
Pelo que vi na web poderia resolver com um --cgroups=host, mas como posso configurar assim o fogbed/containernet?

![Erro fogbed na VM](https://user-images.githubusercontent.com/651557/226464185-768f8a39-6bc8-48e1-bcf8-1664fa86fade.png)

Desde já obrigado

**Comment by EsauM10** [comment]
Eu sugiro utilizar o Ubuntu 20.04, parece que o Containernet está limitado a alguns SO's. Devido a essa limitação, por enquanto o fogbed está funcionando apenas no Ubuntu 20.04. 

Docs Containernet:
https://containernet.github.io/

**Comment by lucasa** [comment]
Ok, certo.
